import { PageCount } from './types';

export interface SlideLayout { type: string; label: string; }

// 每个档位的版式组合
export const layoutPresets: Record<PageCount, SlideLayout[]> = {
  5: [
    { type: 'cover', label: '封面' },
    { type: 'toc', label: '目录' },
    { type: 'content', label: '核心内容 1' },
    { type: 'content', label: '核心内容 2' },
    { type: 'summary', label: '总结' },
  ],
  10: [
    { type: 'cover', label: '封面' },
    { type: 'toc', label: '目录' },
    { type: 'content', label: '核心内容 1' },
    { type: 'content', label: '核心内容 2' },
    { type: 'data', label: '数据展示' },
    { type: 'content', label: '核心内容 3' },
    { type: 'comparison', label: '对比分析' },
    { type: 'content', label: '核心内容 4' },
    { type: 'summary', label: '总结与行动' },
    { type: 'appendix', label: '附录' },
  ],
  15: [
    { type: 'cover', label: '封面' },
    { type: 'toc', label: '目录' },
    { type: 'content', label: '背景与现状' },
    { type: 'data', label: '数据分析 1' },
    { type: 'content', label: '问题定义' },
    { type: 'content', label: '解决方案 1' },
    { type: 'content', label: '解决方案 2' },
    { type: 'data', label: '数据分析 2' },
    { type: 'comparison', label: '方案对比' },
    { type: 'timeline', label: '实施路线图' },
    { type: 'content', label: '资源与预算' },
    { type: 'content', label: '风险评估' },
    { type: 'summary', label: '总结' },
    { type: 'action', label: '下一步行动' },
    { type: 'appendix', label: '附录' },
  ],
  20: [
    { type: 'cover', label: '封面' },
    { type: 'toc', label: '目录' },
    { type: 'content', label: '项目背景' },
    { type: 'content', label: '现状分析' },
    { type: 'data', label: '关键数据 1' },
    { type: 'content', label: '问题定义' },
    { type: 'content', label: '目标设定' },
    { type: 'content', label: '方案概述' },
    { type: 'content', label: '方案详情 1' },
    { type: 'content', label: '方案详情 2' },
    { type: 'data', label: '关键数据 2' },
    { type: 'comparison', label: '方案对比' },
    { type: 'architecture', label: '架构设计' },
    { type: 'timeline', label: '实施路线图' },
    { type: 'content', label: '资源规划' },
    { type: 'content', label: '预算分析' },
    { type: 'content', label: '风险与应对' },
    { type: 'summary', label: '总结' },
    { type: 'action', label: '下一步行动' },
    { type: 'appendix', label: '附录' },
  ],
  25: [
    { type: 'cover', label: '封面' },
    { type: 'toc', label: '目录' },
    { type: 'content', label: '执行摘要' },
    { type: 'content', label: '项目背景' },
    { type: 'content', label: '行业趋势' },
    { type: 'data', label: '市场数据' },
    { type: 'content', label: '现状分析' },
    { type: 'content', label: '问题定义' },
    { type: 'content', label: '目标与KPI' },
    { type: 'content', label: '方案概述' },
    { type: 'content', label: '方案详情 1' },
    { type: 'content', label: '方案详情 2' },
    { type: 'content', label: '方案详情 3' },
    { type: 'data', label: '效果预测' },
    { type: 'comparison', label: '方案对比' },
    { type: 'architecture', label: '技术架构' },
    { type: 'timeline', label: '实施路线图' },
    { type: 'content', label: '资源规划' },
    { type: 'content', label: '预算与ROI' },
    { type: 'data', label: '财务分析' },
    { type: 'content', label: '风险评估' },
    { type: 'content', label: '风险应对策略' },
    { type: 'summary', label: '总结' },
    { type: 'action', label: '下一步行动' },
    { type: 'appendix', label: '附录' },
  ],
};
