import { ThemeConfig, StyleTheme } from './types';

export const themes: Record<StyleTheme, ThemeConfig> = {
  google: {
    name: 'Google 风格',
    primary: '#1A73E8',
    secondary: '#5F6368',
    accent: '#EA4335',
    background: '#FFFFFF',
    text: '#202124',
    lightGray: '#F1F3F4',
    description: '简洁留白、数据驱动、色块分区',
  },
  amazon: {
    name: 'Amazon 风格',
    primary: '#232F3E',
    secondary: '#FF9900',
    accent: '#146EB4',
    background: '#FFFFFF',
    text: '#0F1111',
    lightGray: '#F5F5F5',
    description: '高信息密度、叙事性强、六页纸思维',
  },
  microsoft: {
    name: 'Microsoft 风格',
    primary: '#0078D4',
    secondary: '#50E6FF',
    accent: '#D83B01',
    background: '#FFFFFF',
    text: '#323130',
    lightGray: '#F3F2F1',
    description: '结构清晰、图标体系完整、蓝灰色调',
  },
  deloitte: {
    name: 'Deloitte 风格',
    primary: '#86BC25',
    secondary: '#0D8390',
    accent: '#43B02A',
    background: '#FFFFFF',
    text: '#333333',
    lightGray: '#F2F2F2',
    description: '专业严谨、数据图表规范、脚注完整',
  },
  pwc: {
    name: 'PwC 风格',
    primary: '#D04A02',
    secondary: '#2D2D2D',
    accent: '#EB8C00',
    background: '#FFFFFF',
    text: '#2D2D2D',
    lightGray: '#F5F5F5',
    description: '专业严谨、暖色调、结构化表达',
  },
  brand: {
    name: '炫彩紫色系',
    primary: '#7C3AED',
    secondary: '#A78BFA',
    accent: '#EC4899',
    background: '#FFFFFF',
    text: '#1E1B4B',
    lightGray: '#F5F3FF',
    description: '渐变紫色·科技感·品牌定制',
  },
};
